title: AimonaStudio
SEOTitle: Aimona工作室官方网站


kramdown:
  input: GFM


members: [
  {
    title: "排长的Blog",
    href: "http://paizhang.info/"
  },
    
  {
    title: "妮妙的Pixiv",
    href: "https://www.pixiv.net/member_illust.php?id=11619949"
  },

  {
    title: "Himself65的Blog",
    href: "http://himself65.com/"
  }
]
